# Generated by Django 5.1.4 on 2025-11-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trippath',
            name='trip_list',
        ),
        migrations.RemoveField(
            model_name='trippath',
            name='end_point',
        ),
        migrations.RemoveField(
            model_name='trippath',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='trippath',
            name='start_point',
        ),
        migrations.DeleteModel(
            name='TripList',
        ),
        migrations.DeleteModel(
            name='TripPath',
        ),
    ]
